# 2.1 Kiểu dữ liệu cơ bản
Giống với các ngôn ngữ lập trình khác, Python cũng có các kiểu dữ liệu cơ bản như integers (số
nguyên), floats (số thực), booleans (kiểu dữ liệu True/False) và strings (chuỗi).
Để khai báo biến trong Python không cần chỉ định kiểu dữ liệu trước như những ngôn ngữ
khác mà khi ta gán dữ liệu cho biến thì python tự gán kiểu phù hợp cho biến

## 2.1.1 numbers (số)

In [2]:
x=3
print(type(x))
print(x)
print(x + 1)
print(x - 1)
print(x * 2)
print(x ** 2)
x += 1
print(x)
x *= 2
print(x)
y = 2.5
print(type(y))
print(y, y + 1, y * 2, y ** 2)

<class 'int'>
3
4
2
6
9
4
8
<class 'float'>
2.5 3.5 5.0 6.25


# 2.1.2 Boolean


In [ ]:
t = True
f = False
print(type(t))
print(t and f)
print(t or f)
print(not t)
print(t != f)

2.1.3 Strings (chuỗi)
Chuỗi trong Python có thể được đặt trong dấu nháy đơn ('...') hoặc dấu nháy kép ("...") với

In [3]:
hello = 'hello'
world = "world"
print(hello)
print(len(hello))
hw = hello + ' ' + world
print(hw)
hw12 = '%s %s %d' % (hello, world, 12)
print(hw12)

hello
5
hello world
hello world 12


In [ ]:
s = "hello"
print(s.capitalize())
print(s.upper())
print(s.rjust(7))

# 2.2 Containers
Python cung cấp nhiều cấu trúc dữ liệu để lưu trữ nhiều dữ liệu khác nhau. Các cấu trúc dữ liệu
## 2.2.1 List

In [ ]:
xs = [3, 1, 2]
print(xs, xs[2])
print(xs[-1])
xs[2] = 'foo'
print(xs)
xs.append('bar')
print(xs)
x = xs.pop()
print(x, xs)

Sclicing: Python cung cấp cú pháp đặc biệt để truy cập một phần của list, được gọi là slicing:

In [5]:
nums = list(range(5))
print(nums)
print(nums[2:4])
print(nums[2:])
print(nums[:2])
print(nums[:])
print(nums[:-1])
nums[2:4] = [8, 9]
print(nums)

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


## 2.2.2 Dictionaries

In [1]:
d = {'cat': 'cute', 'dog': 'furry'}
print(d['cat'])
print('cat' in d)
d['fish'] = 'wet'
del d['fish']

cute
True


In [ ]:
d= {'person': 2, 'cat': 4, 'spider': 8}
for animal in d:
    legs = d[animal]
    print('A %s has %d legs' % (animal, legs))
    
for animal, legs in d.items():
    print('A %s has %d legs' % (animal, legs))

# 2.3 Function (Hàm)
Function trong Python được định nghĩa bằng từ khóa def. Ví dụ:

In [ ]:
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'
    
for x in [-1, 0, 1]:
    print(sign(x))

# 2.4 Thư viện (Library)
Thư viện trong Python giống như các thư viện trong các ngôn ngữ lập trình khác, chúng cung cấp
các hàm và cấu trúc dữ liệu sẵn có để giúp chúng ta giải quyết các vấn đề cụ thể. Một số thư
viện phổ biến trong Python như: Numpy, Scipy, Pandas, Matplotlib, Scikit-learn, TensorFlow,
Pytorch, Keras, OpenCV, …


# 2.5 Thư viện Numpy
Numpy là một thư viện quan trọng trong Python, cung cấp nhiều hàm và cấu trúc dữ liệu mạnh mẽ
được sử dụng rộng rãi trong tính toán khoa học và máy học. Một trong những cấu trúc dữ liệu
quan trọng nhất trong Numpy là mảng đa chiều (n-dimensional array) hay ndarray. Mảng đa chiều

In [3]:
import numpy as np
a = np.array([1, 2, 3])
print(type(a))
print(a.shape)
print(a[0], a[1], a[2])
a[0] = 5
print(a)
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

<class 'numpy.ndarray'>
(3,)
1 2 3


In [6]:
a = np.zeros((2, 2))
print(a)
b = np.ones((1, 2))
print(b)
c = np.full((2, 2), 7)
print(c)
d = np.eye(2)
print(d)
e = np.random.random((2, 2))
print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.4491436  0.74227363]
 [0.89140192 0.21719971]]


## 2.5.1 Array indexing

In [ ]:
import numpy as np
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b = a[:2, 1:3]